const advice_list = [
    // Serious
    "Cette semaine, vous pourriez être amené(e) à établir de nouveaux contacts ou à renforcer les liens existants, en cherchant à construire des relations positives et authentiques avec les personnes qui vous entourent.",
    "Cette semaine, vous pourriez être amené(e) à réfléchir sur vos propres comportements et attitudes dans vos relations avec les autres, en cherchant à améliorer votre communication et à vous concentrer sur les aspects positifs de ces relations.",
    "Cette semaine, vous pourriez être encouragé(e) à vous concentrer sur les aspects positifs de vos relations avec les autres, en cultivant la gratitude et en cherchant à nourrir les liens qui vous tiennent à cœur.",
    "Cultivez la gratitude et la reconnaissance envers les personnes qui vous entourent, en exprimant votre appréciation et en nourrissant les relations positives dans votre vie.",
    "Favorisez la communication ouverte et honnête dans vos relations, en exprimant vos sentiments et vos préoccupations de manière respectueuse, pour éviter les malentendus et cultiver la confiance.",
    "Favorisez la compréhension et la compassion dans vos interactions avec les autres, en écoutant activement et en cherchant à comprendre leurs perspectives, même si vous ne les partagez pas.",
    "Il est important de faire preuve de respect et d'ouverture envers les opinions et les points de vue des autres, même s'ils diffèrent des vôtres, pour maintenir des relations harmonieuses et équilibrées.",
    "Il est important de maintenir un équilibre entre donner et recevoir dans vos relations, en offrant du soutien et de l'attention aux autres, tout en veillant à ne pas vous oublier vous-même.",
    "Il est possible que vous ressentiez le besoin de créer des limites saines dans vos relations avec les autres, en veillant à préserver votre propre bien-être et à respecter vos propres valeurs.",
    "Il est possible que vous soyez appelé(e) à faire preuve de patience et de tolérance dans vos relations avec les autres, en faisant preuve de compréhension et en cherchant à résoudre les conflits de manière constructive.",
    "Il est possible que vous soyez encouragé(e) à cultiver la communication et l'écoute active dans vos relations avec les autres, ce qui pourrait renforcer les liens et favoriser une meilleure compréhension mutuelle.",
    "Il est possible que vous soyez encouragé(e) à cultiver la patience et la compréhension dans vos relations avec les autres, en faisant preuve d'empathie et en cherchant à voir les choses du point de vue de l'autre.",
    "Il est possible que vous soyez encouragé(e) à développer votre confiance en vous dans vos interactions avec les autres, en faisant preuve d'assertivité et en défendant vos propres idées et opinions.",
    "Il est possible que vous soyez encouragé(e) à être plus ouvert(e) d'esprit dans vos relations avec les autres, en cherchant à découvrir de nouvelles perspectives et à cultiver la diversité dans votre vie sociale.",
    "Il est possible que vous soyez encouragé(e) à sortir de votre zone de confort et à vous aventurer vers de nouvelles rencontres et de nouvelles expériences, ce qui pourrait enrichir votre vie sociale.",
    "Restez ouvert(e) aux opportunités de rencontres et de connexion avec les autres cette semaine, car de nouvelles relations pourraient apporter une perspective rafraîchissante à votre vie.",
    "Soyez attentif/attentive à la qualité de vos interactions avec les autres, en cherchant à favoriser la communication claire et à éviter les malentendus ou les conflits inutiles.",
    "Soyez attentif/attentive à vos propres besoins ainsi qu'à ceux des autres dans vos relations cette semaine, en pratiquant l'empathie et en cherchant des compromis pour maintenir l'harmonie.",
    "Soyez attentif/attentive aux signes non verbaux et à la communication non verbale dans vos interactions avec les autres, en cherchant à établir une communication claire et à renforcer la compréhension mutuelle.",
    "Soyez ouvert(e) aux possibilités de collaboration et de travail d'équipe cette semaine, en cherchant à construire des relations positives et productives avec les personnes qui vous entourent.",
    "Soyez prêt(e) à accepter les différences et les imperfections des autres, car cela peut renforcer les liens et favoriser la croissance personnelle dans vos relations interpersonnelles.",
    "Soyez prêt(e) à faire des compromis dans vos relations avec les autres, en cherchant à maintenir l'équilibre et l'harmonie tout en respectant les besoins et les limites de chacun.",
    "Vous pourriez être amené(e) à chercher un nouvel équilibre dans vos relations, en déterminant ce qui est important pour vous et en veillant à respecter vos propres limites et besoins.",
    "Vous pourriez être amené(e) à réfléchir sur vos relations actuelles et à prendre des décisions éclairées sur la manière dont vous souhaitez les nourrir et les développer dans le futur.",
    // Custom
    "Comme le disent si bien les américains, \"Go fuck yourself\".",
    "Jouez à Outer Wilds!",
    "On n'est pas bien là?",
    "Pour vous détendre, vous devriez vous mettre au yoga ou aller bruler quelques poubelles.",
]