const love_list = [
    "Love 1",
    "Love 2",
    "Love 3",
    "Love 4",
    "Love 5",
    "Love 6",
    "Love 7",
    "Love 8",
    "Love 9",
    "Love 10",
    "Love 11",
    "Love 12",
    "Love 13",
]