const love_list = [
    // Serious
    "Cette semaine, vous pourriez être amené(e) à réfléchir sur vos propres attentes et besoins dans vos relations amoureuses, en cherchant à cultiver l'amour-propre et à établir des limites saines.",
    "Cette semaine, vous pourriez être amené(e) à renforcer la confiance et la complicité avec votre partenaire, en partageant vos pensées, vos rêves et vos préoccupations de manière authentique et honnête.",
    "Cette semaine, vous pourriez ressentir le besoin de cultiver la complicité et la complicité émotionnelle avec votre partenaire, en partageant des moments de qualité et en nourrissant votre relation avec amour et attention.",
    "Cette semaine, vous pourriez ressentir le besoin de cultiver la créativité et l'exploration dans votre vie sexuelle, en essayant de nouvelles choses et en sortant de votre zone de confort.",
    "Cette semaine, vous pourriez ressentir le besoin de prendre soin de votre bien-être sexuel en prenant le temps de vous détendre, de vous connecter avec votre corps et de vous nourrir émotionnellement pour une expérience sexuelle épanouissante.",
    "Cette semaine, vous pourriez ressentir le besoin de renforcer la confiance et la complicité avec votre partenaire, en partageant vos vulnérabilités et en construisant une connexion émotionnelle solide.",
    "Il est possible que vous ayez envie de vous connecter davantage avec votre partenaire sur le plan physique, en partageant des moments d'intimité et de complicité.",
    "Il est possible que vous ressentiez le besoin de cultiver la complicité et la confiance avec votre partenaire dans votre vie sexuelle, en créant un espace sûr et aimant pour partager vos désirs et vos besoins.",
    "Il est possible que vous ressentiez le besoin de renforcer la communication et la compréhension mutuelle dans votre relation amoureuse, en écoutant activement votre partenaire et en exprimant vos propres besoins et émotions.",
    "Il est possible que vous soyez amené(e) à chercher un nouvel équilibre entre vos besoins personnels et ceux de votre partenaire, en veillant à maintenir une communication ouverte et honnête pour éviter les malentendus.",
    "Il est possible que vous soyez amené(e) à cultiver l'équilibre entre l'indépendance et la coopération dans votre relation, en respectant les espaces et les besoins individuels de chacun.",
    "Il est possible que vous soyez amené(e) à cultiver l'intimité émotionnelle dans votre relation sexuelle, en partageant vos émotions, vos préoccupations et vos désirs avec votre partenaire.",
    "Il est possible que vous soyez encouragé(e) à explorer de nouvelles expériences et aventures avec votre partenaire, en cultivant l'aventure et la découverte dans votre vie amoureuse et sexuelle.",
    "Il est possible que vous soyez encouragé(e) à explorer de nouvelles formes d'intimité et de connexion avec votre partenaire, en restant ouvert(e) à la croissance et à l'évolution de votre relation.",
    "Il est possible que vous soyez encouragé(e) à exprimer vos désirs et vos besoins sexuels de manière claire et respectueuse avec votre partenaire, en favorisant la communication ouverte et honnête dans votre vie sexuelle.",
    "Soyez à l'écoute de vos désirs et de ceux de votre partenaire, en communiquant ouvertement sur vos envies et en créant un espace de confiance pour explorer vos fantasmes et vos besoins sexuels.",
    "Soyez attentif/attentive à la communication non verbale et aux signaux subtils dans votre relation amoureuse, en cherchant à développer une connexion profonde et authentique avec votre partenaire.",
    "Soyez attentif/attentive à la connexion émotionnelle avec votre partenaire pendant vos moments d'intimité, en créant un espace de confiance et d'amour pour une expérience sexuelle épanouissante.",
    "Soyez attentif/attentive à la qualité de la communication dans votre relation, en privilégiant l'écoute active, le respect et la bienveillance pour maintenir une relation saine et épanouissante.",
    "Soyez attentif/attentive aux besoins émotionnels de votre partenaire, en faisant preuve d'empathie, de compréhension et de soutien dans votre relation amoureuse.",
    "Soyez attentif/attentive aux besoins et aux désirs de votre partenaire cette semaine, en cherchant à créer un espace de confiance et d'écoute dans votre relation amoureuse.",
    "Soyez prêt(e) à cultiver la communication ouverte et honnête dans votre relation amoureuse, en favorisant la transparence et l'authenticité pour créer un lien solide avec votre partenaire.",
    "Soyez prêt(e) à écouter et à comprendre les émotions et les préoccupations de votre partenaire, en faisant preuve de compassion et en cherchant à renforcer la compréhension mutuelle dans votre relation amoureuse.",
    "Soyez prêt(e) à exprimer vos désirs et vos limites de manière claire et respectueuse, en favorisant une communication ouverte et honnête avec votre partenaire dans votre vie sexuelle.",
    "Soyez prêt(e) à exprimer vos limites et à respecter celles de votre partenaire, en favorisant une communication claire et consensuelle pour une expérience sexuelle respectueuse et épanouissante.",
    "Soyez prêt(e) à faire preuve d'ouverture d'esprit et de compréhension envers les différences et les défis dans votre relation amoureuse, en cherchant à cultiver la tolérance et la bienveillance.",
    "Soyez prêt(e) à vous connecter avec votre partenaire sur le plan émotionnel avant de vous connecter physiquement, en favorisant la communication, l'intimité et la compréhension mutuelle.",
    "Vous pourriez être amené(e) à vivre des moments d'intimité profonde et de connexion émotionnelle avec votre partenaire, en partageant vos pensées, vos sentiments et vos expériences.",
    "Vous pourriez être encouragé(e) à approfondir la connexion émotionnelle avec votre partenaire, en exprimant vos sentiments et en cultivant l'intimité émotionnelle dans votre relation.",
    "Vous pourriez ressentir un regain de passion et d'énergie dans votre vie sexuelle, en explorant de nouvelles façons d'éveiller votre sensualité et votre créativité.",
    // Custom
    "CULpidon a tiré sa flèche, la chasse est ouverte!",
    "Grosse baise en approche cette semaine.",
    "Pécho, c'est uniquement une histoire de mindset. Alors en avant!",
    "Si vous aviez reçu 1 million d'euros pour chacun de vos rapport sexuels, vous seriez toujours aussi pauvre.",
]