const social_list = [
    "Social 1",
    "Social 2",
    "Social 3",
    "Social 4",
    "Social 5",
    "Social 6",
    "Social 7",
    "Social 8",
    "Social 9",
    "Social 10",
    "Social 11",
    "Social 12",
    "Social 13",
]