const social_list = [
    // Serious
    "Il est possible que vous ayez besoin de définir des limites claires dans vos relations avec les autres, en protégeant votre propre bien-être émotionnel et en favorisant des relations saines et équilibrées.",
    "Il est possible que vous ressentiez le besoin de donner de l'espace et de la liberté à vos proches, en respectant leur individualité et en favorisant des relations basées sur la compréhension et le respect mutuel.",
    "Il est possible que vous ressentiez le besoin de mettre en place des limites saines dans vos relations avec les autres, en respectant vos propres besoins et en favorisant des relations équilibrées et respectueuses.",
    "Il est possible que vous ressentiez le besoin de prendre du temps pour vous connecter avec vos proches, d'échanger et de partager des moments de qualité qui renforcent les liens familiaux et amicaux.",
    "Il est possible que vous ressentiez le besoin de vous entourer de personnes positives et bienveillantes, en vous entourant de ceux qui vous soutiennent et vous inspirent dans votre vie quotidienne.",
    "Il est possible que vous ressentiez le besoin de vous entourer de personnes qui partagent vos valeurs et vos intérêts, en vous entourant d'un cercle social qui vous soutient et vous enrichit sur le plan personnel.",
    "Il est possible que vous soyez confronté(e) à des défis relationnels qui nécessitent de la compréhension, de la patience et de la diplomatie pour les résoudre de manière constructive et bénéfique pour toutes les parties impliquées.",
    "Il est possible que vous soyez confronté(e) à des situations qui nécessitent une communication claire et respectueuse pour éviter les malentendus et favoriser des relations harmonieuses et épanouissantes.",
    "Il est possible que vous soyez encouragé(e) à cultiver la confiance et la loyauté dans vos relations avec les autres, en étant honnête, authentique et en respectant les engagements que vous prenez envers eux.",
    "Il est possible que vous soyez encouragé(e) à exprimer vos besoins et vos attentes de manière assertive dans vos relations avec les autres, en favorisant une communication claire et respectueuse pour maintenir des relations épanouissantes et équilibrées.",
    "Il est possible que vous soyez encouragé(e) à exprimer votre gratitude et à reconnaître la valeur des autres dans votre vie, en cultivant ainsi des relations authentiques et enrichissantes basées sur la gratitude et la reconnaissance.",
    "Il est possible que vous soyez encouragé(e) à pardonner et à laisser aller les rancunes dans vos relations avec les autres, en favorisant la compréhension, la compassion et la résolution pacifique des conflits.",
    "Votre capacité à communiquer de manière claire et respectueuse pourrait être mise en avant cette semaine, vous permettant de résoudre les malentendus et de maintenir des relations positives et épanouissantes.",
    "Votre capacité à écouter attentivement les autres et à exprimer vos opinions de manière respectueuse pourrait être mise en avant cette semaine, vous permettant de développer des relations harmonieuses et équilibrées.",
    "Votre capacité à montrer de la compassion et à offrir un soutien émotionnel pourrait jouer un rôle clé dans vos relations avec les autres, en créant un environnement de confiance et d'harmonie.",
    "Votre capacité à résoudre les conflits de manière constructive et à trouver des solutions bénéfiques pour toutes les parties pourrait être mise en avant cette semaine, vous permettant de maintenir des relations harmonieuses et durables.",
    "Votre empathie et votre capacité à comprendre les autres pourraient être mises en avant cette semaine, vous permettant de tisser des liens solides avec les personnes qui vous entourent et de créer un environnement harmonieux.",
    "Votre ouverture d'esprit et votre capacité à accepter les différences pourraient être mises en avant cette semaine, vous permettant de créer des relations inclusives et diversifiées qui enrichissent votre vie.",
    "Votre sens de l'écoute et de l'empathie pourrait être mis en avant cette semaine, vous permettant de comprendre les besoins et les émotions des autres, et d'établir des relations solides basées sur la compréhension mutuelle.",
    "Votre volonté de compromis et votre capacité à trouver des solutions gagnant-gagnant pourraient jouer un rôle clé dans vos relations avec les autres, en favorisant la coopération et l'harmonie.",
    "Vous pourriez être amené(e) à consacrer du temps et de l'énergie à cultiver vos relations avec les autres cette semaine, en créant des liens solides et en favorisant une communication ouverte et authentique.",
    "Vous pourriez être amené(e) à créer des opportunités de partage et d'échange avec les personnes qui vous entourent, en favorisant la collaboration et la coopération dans vos relations interpersonnelles.",
    "Vous pourriez être encouragé(e) à exprimer vos appréciations et vos encouragements envers les autres, en reconnaissant leur valeur et en cultivant ainsi des relations positives et stimulantes.",
    "Vous pourriez être encouragé(e) à exprimer vos émotions et à être authentique dans vos relations avec les autres, en créant ainsi des liens plus profonds et plus significatifs basés sur la confiance mutuelle.",
    // Custom
    "La vie est finalement très futile, alors la prochaine fois insultez cet automobiliste qui vous a grillé la priorité.",
    "On n'a qu'une famille, celle du sang et celle qu'on choisit.",
    "Rien n'est plus important que les amis... à part peut-être un milliard d'euros?",
    "Vous êtes seul(e), si seul(e). Et il n'y a rien à y faire.",
]