const work_list = [
    // Serious
    "Cette semaine, vous pourriez être motivé(e) à prendre des mesures pour progresser dans votre carrière et atteindre vos objectifs professionnels.",
    "Il est possible que vous ayez besoin de trouver un équilibre entre vos responsabilités professionnelles et vos besoins personnels, en prenant le temps de vous reposer et de vous ressourcer pour être plus performant(e) dans votre travail.",
    "Il est possible que vous ayez l'occasion de développer de nouvelles compétences ou d'explorer de nouvelles opportunités professionnelles, ce qui pourrait vous aider à élargir vos horizons.",
    "Il est possible que vous ressentiez le besoin de prendre du recul et de réfléchir à vos objectifs professionnels à long terme, en vous assurant qu'ils sont alignés sur vos valeurs et vos aspirations.",
    "Il est possible que vous ressentiez le besoin de rechercher un meilleur équilibre entre votre vie professionnelle et votre vie personnelle, en accordant une attention particulière à votre bien-être et à votre santé.",
    "Il est possible que vous ressentiez le besoin de revoir votre stratégie professionnelle et de prendre des mesures pour vous positionner favorablement sur le marché du travail, en mettant en valeur vos compétences et vos talents uniques.",
    "Il est possible que vous soyez confronté(e) à de nouvelles opportunités professionnelles qui nécessitent de la flexibilité et de l'adaptabilité de votre part, vous permettant de vous développer et d'évoluer dans votre carrière.",
    "Il est possible que vous soyez confronté(e) à des défis professionnels qui nécessitent de la créativité et de l'innovation pour les surmonter, en faisant preuve de résilience et de perspicacité.",
    "Il est possible que vous soyez encouragé(e) à sortir de votre zone de confort dans votre carrière, en embrassant de nouvelles opportunités et en prenant des risques calculés pour atteindre vos objectifs professionnels.",
    "La communication claire et efficace pourrait être essentielle dans votre travail cette semaine, vous permettant de vous exprimer avec confiance et d'éviter les malentendus.",
    "Votre ambition et votre détermination pourraient être mis en avant cette semaine, vous poussant à poursuivre vos objectifs professionnels avec passion et persévérance.",
    "Votre communication et vos compétences relationnelles pourraient jouer un rôle clé dans votre travail cette semaine, en vous aidant à établir de bonnes relations avec vos collègues et à résoudre efficacement les conflits.",
    "Votre créativité et votre ingéniosité pourraient être sollicitées dans votre travail cette semaine, vous permettant de trouver des solutions novatrices à des défis professionnels.",
    "Votre détermination et votre engagement pourraient vous aider à faire des progrès significatifs dans votre carrière, même si vous rencontrez des défis sur votre chemin.",
    "Votre persévérance et votre détermination pourraient être mises à l'épreuve dans votre travail en ce moment, vous encourageant à rester concentré(e) sur vos tâches et à surmonter les obstacles.",
    "Votre sens de l'organisation et de la planification pourrait être mis en avant cette semaine, vous permettant de gérer efficacement vos tâches professionnelles et de rester concentré(e) sur vos priorités.",
    "Votre travail acharné et votre engagement pourraient être reconnus et récompensés cette semaine, vous apportant une gratification professionnelle et vous motivant à continuer sur votre lancée.",
    "Vous pourriez être amené(e) à prendre des décisions importantes concernant votre carrière cette semaine, en évaluant soigneusement les avantages et les inconvénients pour prendre la meilleure décision possible.",
    "Vous pourriez être amené(e) à prendre des décisions importantes concernant votre carrière cette semaine, en pesant soigneusement les options et en suivant votre intuition.",
    "Vous pourriez être amené(e) à prendre des initiatives et à assumer de nouvelles responsabilités dans votre travail, ce qui pourrait vous permettre de progresser dans votre carrière et de gagner en confiance en vous.",
    "Vous pourriez être confronté(e) à de nouvelles responsabilités professionnelles ou à des défis qui nécessitent de la confiance en vous et du courage pour les surmonter.",
    "Vous pourriez être encouragé(e) à élargir votre réseau professionnel et à développer de nouvelles relations avec des collègues ou des contacts dans votre domaine, ce qui pourrait vous ouvrir de nouvelles opportunités de carrière.",
    "Vous pourriez être encouragé(e) à explorer de nouvelles voies professionnelles ou à prendre des initiatives audacieuses dans votre carrière, en faisant preuve de confiance en vous et en osant sortir de votre zone de confort.",
    "Vous pourriez vous sentir inspiré(e) à collaborer avec vos collègues ou à participer à des projets d'équipe, ce qui pourrait vous permettre d'atteindre des objectifs communs de manière efficace.",
    // Custom
    "Macron a voulu faire le beau, et vient de reculer votre retraite de 2 ans. Pas de chance!",
    "Macron, démission!",
    "Que vous aimiez votre boulot ou pas, n'oubliez jamais que c'est la faute du capitalisme.",
    "Travailler c'est surfait. :)",
]